export const RPC_URLs = [
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV32Q2QWkZC8R74NCmjoJxwjg",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV30H1Wn1Y5UR76heYikDqYY7",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV31YItEFY5sR74IOrifuQQh_",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV33oUIZqY5sR74IQrifuQQh_",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV3342bIFY5sR74IRrifuQQh_",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV30Fs5JOY5wR74ISrifuQQh_",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV30Os4OjY5wR74ITrifuQQh_",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV30XA6FsY5wR74IUrifuQQh_",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV30gdFMpY5wR74IVrifuQQh_",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV30pB1d4Y5wR74IWrifuQQh_",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV30vlHEVY5wR74IXrifuQQh_",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV30liaxPZC8R74M4mjoJxwjg",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV3013ihiZC8R74M5mjoJxwjg",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV309p-BOZC8R74M6mjoJxwjg",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV31FrZxQZC8R74M7mjoJxwjg",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV31PDj9yZC8R74M8mjoJxwjg",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV31UgSaWZC8R74M9mjoJxwjg",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV31seH2YZC8R74M-mjoJxwjg",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV31yt0wlZC8R74M_mjoJxwjg",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV315MiDkZC8R74NAmjoJxwjg",
  "https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvFHGgG8vUoprYSFl1RGV31-DezbZC8R74NBmjoJxwjg",
  ]
  
  